doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: '%env(string:PUBLIC_API_DB_NAME)%'
                user: '%env(string:DB_USERNAME)%'
                password: '%env(string:DB_PASSWORD)%'
                host: '%env(string:DB_HOST)%'
                port: '%env(int:DB_PORT)%'
                charset: UTF-8
                driver: sqlsrv
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AuthorizationServer:
                is_bundle: false
                type: 'attribute'
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Client/Entity'
                prefix: 'App\Shared\Infrastructure\Client\Entity'
                alias: App
