league_oauth2_server:
  authorization_server:
    private_key: /var/oauth/public-api
    private_key_passphrase: null
    encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'

    enable_client_credentials_grant: true

  resource_server:
    public_key: /var/oauth/public-api.pub

  scopes:
    available:
      - public-api
    default:
      - public-api

  persistence:
    doctrine:
      entity_manager: default

  client:
    classname: App\Shared\Infrastructure\Client\Entity\Client
