security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    users_in_memory: { memory: null }
  firewalls:
    api_doc:
      pattern: '^/%public_api_prefix_url%/api/doc$'
      security: false
    api_token:
      pattern: '^/%public_api_prefix_url%/token$'
      security: false
    api:
      pattern: '^/%public_api_prefix_url%/api'
      security: true
      stateless: true
      oauth2: true

  access_control:
    - { path: '^/%public_api_prefix_url%/api', roles: ROLE_OAUTH2_PUBLIC-API }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon

