trikoder_oauth2:
    authorization_server:
        private_key: /var/oauth/public-api
        private_key_passphrase: null
        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'

        grant_types:
            client_credentials:
                enable: true
                access_token_ttl: ~

    resource_server:
        public_key: /var/oauth/public-api.pub

    scopes:
        - public-api

    persistence:
        doctrine: null
