version: '3.9'
services:
  testapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    depends_on:
      - testdb
    environment:
      - APP_DEBUG=true # needs to be true to generate container xml cache file
      - APP_ENV=test
      - PUBLIC_API_DB_NAME=public_api_db_test
      - DB_PASSWORD=Asd12345
      - DB_USERNAME=sa
      - DB_CONTAINER_NAME=testdb
      - SECURITY_KEY_HEX=31faa44d680828f50bea589270333f718b4128c609e9f37b35ec27d0e63cbe8e
      - API_CONTAINER_NAME=public_api_testapi
  testdb:
    image: 'public.ecr.aws/s6z8v3g0/inosadocker/database:release-1.0.2'
    environment:
      - DB_DATABASE=public_api_db_test
      - DB_PASSWORD=Asd12345
      - DB_USERNAME=test
      - SA_PASSWORD=Asd12345
      - ACCEPT_EULA=Y