version: '3.9'
services:
  php:
    container_name: public_api_php
    build:
      context: .
#      args:
#        - HOST_IP=${HOST_IP}
#        - ENV=${ENV}
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      - ENV=dev
    volumes:
      - .:/var/www/html
    networks:
      - inosa_dev
      - reverse-proxy

networks:
  inosa_dev:
    external:
      name: inosa_dev
  reverse-proxy:
    external:
      name: reverse-proxy