services:
  App\Shared\Infrastructure\Client\PublicApiClientPersister: ~
  App\AuthorizationServer\CreatePublicApiClient\Domain\Client\ClientPersisterInterface: '@App\Shared\Infrastructure\Client\PublicApiClientPersister'
