monolog:
    handlers:
        info:
            type: stream
            path: php://stderr
            level: info
            formatter: monolog.formatter.line
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size: 50
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
