oauth2:
  resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
  prefix: '%public_api_prefix_url%'

public-api:
  resource: 'routes/public-api-routes.yaml'
  prefix: '%public_api_prefix_url%'

healthz:
  path: '%public_api_prefix_url%/healthz'
  controller: App\AuthorizationServer\Healthz\HealthzController::healthz
  methods: GET

kernel:
  resource: ../src/Kernel.php
  type: annotation
