oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'

get_folders_basic_structure:
    path: /api/folders-basic-structure/without-metrics
    controller: App\AuthorizationServer\GetFoldersBasicStructure\UI\GetFoldersBasicStructureController::getFoldersBasicStructure
    methods: GET
    defaults:
        oauth2_scopes: [ 'public-api' ]