parameters:
  default_db_port: 1433
  env(DB_PORT): '%default_db_port%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $apiUrl: 'http://%env(string:API_CONTAINER_NAME)%/internalapi/public-api'
      $reportsApiUrl: 'http://%env(string:REPORTS_CONTAINER_NAME)%/public-api'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Shared/Infrastructure/Client/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\AuthorizationServer\CreatePublicApiClient\Domain\Client\ClientCreator:
    arguments:
      $clientPersister: '@App\Shared\Infrastructure\Client\ClientPersister'

  App\Shared\Infrastructure\Repository\AccessTokenRepository:
    arguments:
      - '@League\Bundle\OAuth2ServerBundle\Repository\AccessTokenRepository'

  League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface: '@App\Shared\Infrastructure\Repository\AccessTokenRepository'

