#!/usr/bin/with-contenv sh
0
if [[ -z $SECURITY_KEY_HEX ]]; then
  echo -e "\033[0;31mno SECURITY_KEY_HEX provided. it has to be 256-bit hex code\033[0m"
  exit 1
fi
if [[ ! -d /var/oauth ]]; then
  mkdir /var/oauth
fi
certtool --generate-privkey --outfile /var/oauth/public-api --key-type=rsa --sec-param=high --seed=$SECURITY_KEY_HEX
openssl rsa -in /var/oauth/public-api -pubout > /var/oauth/public-api.pub
